### ISSUE TITLE
[Bug] Special characters are not properly displayed

### ISSUE THREAD

**Issue by gorkat** [Ethery/ProjectStarLegacy#2]
In the dialogues with the PNJ, special characters were not displayed properly.

For instance, when I have a word containing some special characters like : 
* é
* è
* ç

Then they are replaced by some <?> tokens instead.

**Comment by Ethery** [comment]
Yeah the font we use haven't the special characters sadly. We're on the way to found one to replace it.

**Comment by Ethery** [comment]
The font will be changed on the 0.4 ;)

**Comment by gorkat** [comment]
I've tested the v0.4 and unfortunatly, special characters are still not displayed properly :/

![bug](https://cloud.githubusercontent.com/assets/12508241/24591147/c60a12fe-17fa-11e7-89fc-e140f9fcfe3f.PNG)

**Comment by Ethery** [comment]
Is occurs that the build of the XML files that contains the texts are not encoded properly ... we will work on it ;)
