### ISSUE TITLE
[Bug] Mouse pointer disappears

### ISSUE THREAD

**Issue by gorkat** [Ethery/ProjectStarLegacy#3]
The mouse pointer disappears when I navigate in the game menus, so I can't click on the buttons (but the navigation works fine with a game controller).

**Comment by Ethery** [comment]
The mouse is not used ine the game ;) exclusice controller/ keyboard game :p

**Comment by Ethery** [comment]
The mouse is not used ine the game ;) exclusice controller/ keyboard game :p

**Comment by gorkat** [comment]
My bad :) Maybe you could add an entry in the main menu to explain the main controls ?
