### ISSUE TITLE
[Enhancement] [Animations] Rotate the weapon according to the shooting angle

### ISSUE THREAD

**Issue by gorkat** [Ethery/ProjectStarLegacy#5]
When I shoot with my weapon, I expect the weapon to rotate according to the shooting angle.

It could be awesome if you can animate the weapon to do this !

**Comment by Ethery** [comment]
Corrected in 0.3 ;)

**Comment by gorkat** [comment]
Hey ! I would like to test the 0.3 version of the game before you close the thread ;)

**Comment by Ethery** [comment]
Its in build i'll up it soon ;)
