### ISSUE TITLE
[Enhancement][Interaction] Add a return button in the options menu

### ISSUE THREAD

**Issue by gorkat** [Ethery/ProjectStarLegacy#6]
Even though the option menu is not developed yet, It could be great if you can add a return button on this view. I clicked on the option button in the menu, and I've landed somewhere I couldn't go back from. I was forced to leave the game from the Windows task manager (`ctrl + alt + del`).

You can add a button or maybe disable the options entry in the main menu until this part has been developed.

What do you think about that ?

**Comment by Ethery** [comment]
Option menu wasn't implkemented yet so from now the option button doesn't do anything at all ;)
