### ISSUE TITLE
[Bug] Weapon rotation does not take into account the character's position

### ISSUE THREAD

**Issue by gorkat** [Ethery/ProjectStarLegacy#8]
When the character goes backward, the weapon is not displayed in the right direction.

![weapon](https://cloud.githubusercontent.com/assets/12508241/24591178/7d02c064-17fb-11e7-8ae1-bb7028e9e3f2.PNG)

**Comment by Ethery** [comment]
Ho ! that's a mess.. I'll work on it xD

**Comment by gorkat** [comment]
I agree, the character seems to be committing hara-kiri xD

**Comment by Ethery** [comment]
Right XD it's fixed on our dev preview ;) we'll see on the next version it should be fixed :)

**Comment by gorkat** [comment]
Good :+1:
